app:
  scheduler:
    enable: true
    interval: 150s
    force-check-delay: 10s
  database-access-type: jdbc
  retry-max-attempts: 10
  retry-delay: 400
  retry-exponential: 2

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

spring-doc:
  swagger-ui:
    path: /swagger-ui


