app:
  telegram-token: ${TELEGRAM_API_KEY}
  retry-max-attempts: 10
  retry-delay: 400
  retry-exponential: 2

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

spring-doc:
  swagger-ui:
    path: /swagger-ui
